- name: Install PHP and some related packages
  vars:
    packages:
      - php
      - php-fpm
      - php-cli
      - php-curl
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    update_cache: true
    state: latest
