- name: Install Nginx
  vars:
    packages:
      - nginx-core
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    update_cache: true
    state: latest

- name: Delete the default nginx landing page
  ansible.builtin.file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
